version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123456
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nextjs:
    build: .
    container_name: my-nextjs
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://admin:admin123456@postgres:5432/ecommerce?schema=public"
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    container_name: my-nginx
    restart: always
    depends_on:
      - nextjs
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pgdata:
